'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('state:get'),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  correctDay: (key, correction) => ipcRenderer.invoke('day:correct', { key, correction }),
  addRule: (rule) => ipcRenderer.invoke('rules:add', rule),
  toggleRule: (id) => ipcRenderer.invoke('rules:toggle', id),
  deleteRule: (id) => ipcRenderer.invoke('rules:delete', id),
  submitDay: (key) => ipcRenderer.invoke('day:submit', key),
  addProject: (p) => ipcRenderer.invoke('projects:add', p),
  updateProject: (id, patch) => ipcRenderer.invoke('projects:update', { id, patch }),
  deleteProject: (id) => ipcRenderer.invoke('projects:delete', id),
  assignBlock: (key, idx, projectId, keywords) => ipcRenderer.invoke('day:assign', { key, idx, projectId, keywords }),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  saveSheets: (patch) => ipcRenderer.invoke('sheets:save', patch),
  exportSheets: (ym) => ipcRenderer.invoke('sheets:export', ym),
  shareSheets: (cfg) => ipcRenderer.invoke('sheets:share', cfg),
  resolveReview: (arg) => ipcRenderer.invoke('review:resolve', arg),
  recoruCSV: (range) => ipcRenderer.invoke('recoru:csv', range),
  dismissFolderHint: (code) => ipcRenderer.invoke('folder:dismiss', code),
  setPrivate: (minutes) => ipcRenderer.invoke('private:set', minutes),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  adminSetup: (pw) => ipcRenderer.invoke('admin:setup', pw),
  adminUnlock: (pw) => ipcRenderer.invoke('admin:unlock', pw),
  adminLock: () => ipcRenderer.invoke('admin:lock'),
  adminChange: (arg) => ipcRenderer.invoke('admin:change', arg),
  adminSavePolicy: (p) => ipcRenderer.invoke('admin:savePolicy', p),
  addTeam: (obj) => ipcRenderer.invoke('team:add', obj),
  joinTeam: (code) => ipcRenderer.invoke('team:join', code),
  switchTeam: (id) => ipcRenderer.invoke('team:switch', id),
  removeTeam: (id) => ipcRenderer.invoke('team:remove', id),
  teamInvite: (id) => ipcRenderer.invoke('team:invite', id),
  renameTeam: (id, label) => ipcRenderer.invoke('team:rename', { id, label }),
  addCalEvent: (ev) => ipcRenderer.invoke('cal:add', ev),
  deleteCalEvent: (id) => ipcRenderer.invoke('cal:delete', id),
  openUrl: (url) => ipcRenderer.invoke('misc:openUrl', url),
  openScreenSettings: (pane) => ipcRenderer.invoke('perm:openSettings', pane),
  importFolderProjects: () => ipcRenderer.invoke('projects:importFolder'),
  addWatchRoot: () => ipcRenderer.invoke('watch:addRoot'),
  removeWatchRoot: (root) => ipcRenderer.invoke('watch:removeRoot', root),
  relaunchApp: () => ipcRenderer.invoke('app:relaunch'),
  importCalendar: () => ipcRenderer.invoke('calendar:import'),
  setTeamStatus: (memberId, dateKey, status) => ipcRenderer.invoke('team:setStatus', { memberId, dateKey, status }),
  reseedDemo: () => ipcRenderer.invoke('demo:reseed'),
  onUpdate: (cb) => ipcRenderer.on('state:update', (e, state) => cb(state))
});
